### PR TITLE
Force scale=1 to avoid clipped screenshots

### PR DESCRIPTION
**Pull request by tokland**
Required by https://github.com/EyeSeeTea/project-monitoring-app/issues/296

### CODE REVIEW

**Comment by SferaDev** [comment]
Tested on metadata-sync and windows 10, everything works as expected and better than before.

LGTM

**Review by SferaDev — APPROVED** [review]

**Comment by adrianq** [comment]
@tokland Can you please bring this change into metadata sync as well? You can just add it to the PR you are already preparing. @SferaDev Correct me if I am wrong but I didn't see this change as part of any of your PR, right?

**Comment by adrianq** [comment]
@tokland Btw I am accepting this but I guess you should create a PR in Project Monitoring, right? (Do not forget about my previous comment as well)

**Comment by SferaDev** [comment]
> @tokland Can you please bring this change into metadata sync as well? You can just add it to the PR you are already preparing. @SferaDev Correct me if I am wrong but I didn't see this change as part of any of your PR, right?

Yeah we tested this together with tokland as part of a meeting yesterday but didn't commit it to any open PR.

**Comment by tokland** [comment]
Uploaded to those open PRs:

project-monitoring-app: https://github.com/EyeSeeTea/project-monitoring-app/pull/303
metadata-synchronization: https://github.com/EyeSeeTea/metadata-synchronization/pull/617

**Comment by tokland** [comment]
As a note. SVGs are not being rendered on the screenshot. Apparently, this ticket solved it, but we'd need to add more js code to the mix. The tools is big enough, I don't think it's a big gain to see those buttons.

https://github.com/niklasvh/html2canvas/issues/95

**Comment by adrianq** [comment]
Thanks guys! I agree is not a big change to have SVGs rendered properly. My main concern atm and, in particular, for project monitoring is to be able to capture iframe but this is a battle for another life ;)

**Pull request merged**
